name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull codespaceroot/tukula-web-plataform:latest
    - name: Delete Old docker container
      run: sudo docker rm -f tukula-web-plataform || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:4010 --name tukula-web-plataform codespaceroot/tukula-web-plataform
